### ISSUE TITLE
new ci builds fail on unit tests

### ISSUE THREAD

**Issue by btel** [mamba-org/quetz#109]
with the following error:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    """
    h2/frame_buffer
    ~~~~~~~~~~~~~~~
    
    A data structure that provides a way to iterate over a byte buffer in terms of
    frames.
    """
>   from hyperframe.exceptions import InvalidFrameError, InvalidDataError
E   ImportError: cannot import name 'InvalidDataError' from 'hyperframe.exceptions' (/home/runner/test_env/lib/python3.8/site-packages/hyperframe/exceptions.py)

/home/runner/test_env/lib/python3.8/site-packages/h2/frame_buffer.py:9: ImportError
```
https://github.com/mamba-org/quetz/pull/108/checks?check_run_id=1153496549

It's likely due to a recent release of h2 4.0.0 (known to work with 3.2.0): https://github.com/python-hyper/hyper-h2/releases/tag/v4.0.0

**Comment by wolfv** [comment]
ouch! can we pin hyperframe for now?

**Comment by btel** [comment]
yes, I am on it

**Comment by btel** [comment]
pinning h2<4.0 seems to work. I don't understand though, why 4.0 is installed in the first place. If I get it right, it's a dependency of httpx=0.12, but httpx pins the h2 to 3.* branch:

https://github.com/encode/httpx/blob/6e40c1b26ac3526bfe4115c00c028899d37e551e/setup.py#L62
