### PR TITLE
pin h2 version, fixes #109

### LINKED ISSUE #109: new ci builds fail on unit tests
with the following error:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    """
    h2/frame_buffer
    ~~~~~~~~~~~~~~~
    
    A data structure that provides a way to iterate over a byte buffer in terms of
    frames.
    """
>   from hyperframe.exceptions import InvalidFrameError, InvalidDataError
E   ImportError: cannot import name 'InvalidDataError' from 'hyperframe.exceptions' (/home/runner/test_env/lib/python3.8/site-packages/hyperframe/exceptions.py)

/home/runner/test_env/lib/python3.8/site-packages/h2/frame_buffer.py:9: ImportError
```
https://github.com/mamba-org/quetz/pull/108/checks?check_run_id=1153496549

It's likely due to a recent release of h2 4.0.0 (known to work with 3.2.0): https://github.com/python-hyper/hyper-h2/releases/tag/v4.0.0

### PR DESCRIPTION
**Pull request by btel**

### CODE REVIEW

**Comment by wolfv** [comment]
thx!
